spring:
 datasource:
   url: jdbc:h2:mem:/~/test
   username: sa
   # 작은따옴표로 묶고 앞에 {cipher} 라 적으면 암호화된 값이라는 것을 명시하는 것이다.
   password: '30baf106cffc63bbca602196fbd0242494a4e7077995e6acedcaf8f656e7f64f'
   driver-class-name: org.h2.Driver

token:
  expiration_time: 86400000
  secret: FOJ2@#FJ33TF@#5Ffom#!@3@kkf2#$2FF234f2#gmFOJ2@#FJ33TF@#5Ffom#!@3@kkf2#$2FF234f2#gm-application

gateway:
  ip: 192.168.0.8