spring:
 datasource:
   url: jdbc:h2:mem:/~/test
   username: sa
   # 작은따옴표로 묶고 앞에 {cipher} 라 적으면 암호화된 값이라는 것을 명시하는 것이다.
   password: '{cipher}AQA3A6sSh1IHyUWDN6Yw7xuCctLMbC9t/Uf7FsYD/pSLDR1izQRlVwvVPEHJYD3Rs6m8XwSWVkpwp0N3rMEYJMtZDJNrsD48c7h6iPaBreXV3j5NzPgvdS35QQT1s+xaajqpIU8r87jRtbqeUTvgNEbwWTjHdeb+hvQCeoXrnnwAHiBGe+OWVn5qSlXDHXbTahmAbkXnH2zruzgZ8DFO6c+b6oYeRr+btz8I8T86jQFgKLctDkLqwIKPmtvxGdQ0yY2KC715inLKptJnResNBLMvRvvKCqIydNc/iyrXos4nzKDs/5wThh61yOzm5A7XlOTpshc1DV+YNGS0tRKXUYjRA7qXc3EgLsHCPJRlWRUMa4C7jKO0ltiYhknEVnTtCJc='
   driver-class-name: org.h2.Driver

gateway:
  ip: 192.168.0.8