spring:
 datasource:
   url: jdbc:h2:mem:/~/test
   username: sa
   # 작은따옴표로 묶고 앞에 {cipher} 라 적으면 암호화된 값이라는 것을 명시하는 것이다.
   password: '{cipher}AQCFaS3imzykIx5L8LFVODj9TxwJHJSHJswljs+hZTj5rL2nuxQp2lsQ6KBzFFTBrqo52P3SuxiwqQYB40XfJdLaQ3P8qm+H+IU/TaDyxLSA4oi70BywKlXjmRQGYCmHvm62LpJ/XXM4H64xb8oifrL4T2jObsMrloQuEOFdNQHwhWLYYZ6iQBfL+HswFCKZgiJ0Q/H1r+IHi1WiT9ON1ouSiJx37+W3+mPHib+pL7xHbGklnXJvsFJa3WmikDYj/dV1muy7nL4TUWo8VP00AaKMXO7CgtNCPT2ZIiBeFX7lCVGdCZdKy+1G4WnhDpgYDxCVOge4qQr3iCyNrq/xg29HfmBgnmVB/49QhhYvgY7sqriWrLxbTDQ8dNEWJO2/tII='
   driver-class-name: org.h2.Driver

token:
  expiration_time: 86400000
  secret: '{cipher}AQCX9U1VQqMqgBuodlmJ5VyrbIfSlc2NZgGvcUyvk5aE2urQjTQNe/9ADinmEQrOxiBV8OjmMl0PFHWZA5vhdKbT6KS86+qz8eSPslFG8ch+Us7azHbaaKdehgGAf5Xnrs1rUtDKBPGSC4jmneXADQZjIt8RKq26VyglVnM6398PRxKvVfzeoo6nRlpH2b18mBzsdlIly7khjB0R563yJgNoQICdoY9Hk6sT8ov7zA5RG9W6TXtvEtuf4nrxLxzqF1/e1dy0HV9C5ba6bNiu0N7gvlYUkfcvd/u0zhKSgUC2I3ANX1mo5WVx8ofmwTO1qWqH4LlguGst7dOBy7wYXSWqKJN9TLtr5MhV9PhRK/f5I/7qdvF6TmMC82EC5q/mDcsFnT/WWLZxKISvS4z9Bn+9BAf7FC0C3KNT3NxJraY9iusLhzS/6ywIJdkAhY+jhCzd4k5VfZE+pWaaZ7+fGP0tSmpdsOEOZc3cLI2qQ8FPgE2b7EcYYI8QJhiRNWKsvT2kJ9jzvmuncPgjG2V3+Y+P'

order-service:
  url: http://order-service/%s/orders